#
# github.com/talialy/dots
# 
# Some dotfiles for yazi :)
#
#

[manager]
show_hidden = true
show_symlink = true
sort_by = "extension"
sort_dir_first = true
scrolloff = 200 # make it so that it always centers

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
books = [
{ run = 'zathura "$@"', orphan = true, for = "unix"}
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
prepend_rules = [
	{ name = "*.pdf", use = "books" },

]
