shell = "bash -c '{}'"


[[items]]
file = "~/.config/waybar/colors.css"
template = "waybar"
rewrite = true
hook = "killall waybar; waybar &"

[[items]]
file = "~/.config/kitty/colors.conf"
template = "kitty"
subtemplate = "default"
rewrite = true
hook = "kill -SIGUSR1 $(pidof kitty)"

[[item]]
file= "~/.config/mako/config"
template = "mako"
rewrite = false
start = "#flavour"
end = "#end"
hook = "killall mako; mako &"


[[item]]
file= "~/.config/nvim/lua/plugins/colors.lua"
template="nvim"
rewrite = false
start="--# Start flavours"
end="--# End flavours"
hook=""


[[item]]
file= "~/.config/rofi/themes/theme.rasi"
template = "rofi"
rewrite = true


# custom software you'll want to add :)
# CHANGE FOR YOUR USE CASE

[[item]]
file = "~/.var/app/dev.vencord.Vesktop/config/vesktop/themes/base16.css"
template = "discord"
rewrite = true

[[item]]
file = "~/Minmax/.obsidian/snippets/colors.css"
template = "obsidian"
rewrite = true
